CREATE TABLE active_flights ( id SERIAL PRIMARY KEY, origin VARCHAR NOT NULL, destination VARCHAR NOT NULL, numPassengers INTEGER NOT NULL)
INSERT INTO active_flights (origin, destination, numPassengers) VALUES ('New York', 'Toronto', 0)
INSERT INTO active_flights (origin, destination, numPassengers) VALUES ('Toronto', 'New York', 0)
INSERT INTO active_flights (origin, destination, numPassengers) VALUES ('London', 'Toronto', 0)
INSERT INTO active_flights (origin, destination, numPassengers) VALUES ('London', 'New Delhi', 0)
INSERT INTO active_flights (origin, destination, numPassengers) VALUES ('Dubai', 'Toronto', 0)
INSERT INTO active_flights (origin, destination, numPassengers) VALUES ('New Delhi', 'Dubai', 0)
INSERT INTO active_flights (origin, destination, numPassengers) VALUES ('New York', 'Milan', 0)
INSERT INTO active_flights (origin, destination, numPassengers) VALUES ('Los Angeles', 'Toronto', 0)
INSERT INTO active_flights (origin, destination, numPassengers) VALUES ('Las Vegas', 'Toronto', 0)